In [14]:
import pandas as pd

In [15]:
df_boston=pd.read_csv('sample_data/Boston House Prices.csv')
df_boston

Rooms  Distance  Value
0    6.575    4.0900   24.0
1    6.421    4.9671   21.6
2    7.185    4.9671   34.7
3    6.998    6.0622   33.4
4    7.147    6.0622   36.2
..     ...       ...    ...
501  6.593    2.4786   22.4
502  6.120    2.2875   20.6
503  6.976    2.1675   23.9
504  6.794    2.3889   22.0
505  6.030    2.5050   11.9

[506 rows x 3 columns]

**1 Linear Regression with Scikit-learn**

In [16]:
from sklearn import linear_model

**1.1 Define the dependent and independent variable**

In [17]:
#dependent variable
y=df_boston['Value']

#independent variables
x=df_boston[['Rooms', 'Distance']]



**1.2 Fitting the Model**

N/B: We do not need to add the constant as sklearn adds it by default


In [19]:
lm=linear_model.LinearRegression()

lm.fit(x, y)


LinearRegression()

**1.3 Predicting values**

In [20]:
lm.predict(x)

array([25.23262311, 24.30597474, 31.03025338, 29.9197274 , 31.23113776,
       24.92052548, 20.99628003, 22.59515685, 17.89792552, 21.43016488,
       24.59312806, 21.29554669, 19.86012857, 20.02480328, 21.19854962,
       18.91052046, 19.79946305, 20.16587486, 15.24036623, 17.62554884,
       16.24441157, 19.82577837, 21.36632302, 18.52848931, 19.65425152,
       16.82067934, 18.81534563, 20.76312523, 24.70679323, 26.17680132,
       17.71571146, 20.84706509, 19.68285587, 17.39216584, 20.85532906,
       19.22540394, 18.42427779, 18.77543693, 19.75391977, 26.04958067,
       29.82538634, 27.7461615 , 22.45651299, 22.82617229, 21.57637181,
       17.86689491, 18.78224174, 21.21771802, 15.7523132 , 17.64542212,
       21.17812468, 22.51593928, 26.00129836, 21.48617409, 20.7648873 ,
       33.41670435, 26.03470634, 29.42393915, 23.26887906, 20.91861579,
       19.42498135, 21.20638654, 25.71803969, 28.7805479 , 32.39778062,
       23.95685233, 19.52974218, 20.27518634, 17.77558538, 20.33

In [22]:
#if we want to select the first five values inthe array
lm.predict(x)[:5]

array([25.23262311, 24.30597474, 31.03025338, 29.9197274 , 31.23113776])

**1.4 Generate Regression Table**

In [23]:
#r2 score
lm.score(x,y)

0.4955246476058477

In [24]:
#coefficient
lm.coef_

array([8.80141183, 0.48884854])

In [25]:
#intercept
lm.intercept_


np.float64(-34.636050175473315)